name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'enhancement'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'bug'
  - title: 'ğŸ§¹ Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'style'
      - 'documentation'
  - title: 'ğŸ›  Release Process'
    labels:
      - 'release'
      - 'ci'
      - 'major'
      - 'minor'
      - 'patch'

change-template: '- $TITLE #$NUMBER (@$AUTHOR)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: 'patch'
template: |
  ## $RESOLVED_VERSION

  ### Highlights

  ## Detail

  ## Screens

  $CHANGES
